spring:
  application:
    name: s1rates
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: main
      username: user
      password: user
encrypt:
  key: ABCDEFGHIJKLMNOPQRSTUVWXYZ
management:
  endpoints:
    web:
      exposure:
        include: refresh
